import { ChatInfo, ProtoChatMemberUser } from '@modules/chat/stores/chats';
import { User } from '@modules/user/stores/profile';

export type RootStackParamList = {
	Onboarding: undefined;
	Posts: undefined;
	SignIn: undefined;
	SignUp: undefined;
	MainTabs: undefined;
	PostDetail: { postId?: string; };
	PostsInteresting: undefined;
	Chat: { chatId?: string; userChatId?: string; tag?: string; selectedChat?: ChatInfo; previewUser?: User; messageId?: string; scrollToReactionMessageId?: string; scrollToMentionMessageId?: string; };
	ChatProfile: { chatId?: string; userId?: string; tag?: string; selectedChat?: ChatInfo; previewUser?: ProtoChatMemberUser; };
	ChatSettings: { chatId?: string; selectedChat?: ChatInfo; };
	UserPage: { userId?: string; tag?: string; };
	UserSubs: { userId?: string; };
	UserSubscribers: { userId?: string; };
	UserFriends: { userId?: string; };
	CreatePost: undefined;
	CreateGroupChat: undefined;
	CreateChannelChat: undefined;
	ChatSettingsLinks: { chatId?: string; };
	ChatSettingsMembers: { chatId?: string; selectedChat?: ChatInfo; };
	Settings: undefined;
	ChatSettingsType: { chatId?: string; };
	ProfileSettings: undefined;
	PrivacySettings: undefined;
	PrivacySetting: { type?: string; };
	SessionsSettings: undefined;
	ModerationSettings: undefined;
	BeModeratorSettings: undefined;
	MyModerationRequestsSettings: undefined;
	LanguageSettings: undefined;
	MemorySettings: undefined;
	CachedChats: undefined;
	CachedMedia: undefined;
	CustomizationSettings: undefined;
	ThemeSettings: undefined;
	WallpapersSettings: undefined;
	ChatWallpapersSettings: undefined;
	BgColorSettings: undefined;
	BtnColorSettings: undefined;
	PrimaryColorSettings: undefined;
	TextColorSettings: undefined;
	SecondaryTextColorSettings: undefined;
	AllThemeSettings: undefined;
	RadiusSettings: undefined;
	BorderColorSettings: undefined;
	BtnHeightSettings: undefined;
	BtnRadiusSettings: undefined;
	InputBgSettings: undefined;
	InputHeightSettings: undefined;
	InputRadiusSettings: undefined;
	StickerSettings: undefined;
	SubscriptionSettings: undefined;
	TestPosts: undefined;
	TestDetail: { item?: any; };
	ChatSettingsLinkedChat: { selectedChat: ChatInfo; };
	ChatSettingsAllowedReactions: { selectedChat: ChatInfo; };
	TestNativeChat: undefined;
};

export type MainTabParamList = {
	Posts: undefined;
	GlobalSearch: undefined;
	Chats: undefined;
	Notifications: undefined;
	Profile: { tag?: string; };
};

