export const SECURITY_CONFIG = {
	E2E_ENCRYPTION_ENABLED: false,
	HMAC_SIGNING_ENABLED: false,
	NONCE_VALIDATION_ENABLED: true,
	TIMESTAMP_VALIDATION_ENABLED: true,
	TOKEN_IN_HEADER: true,
	AUTO_RECONNECT: true,
	MAX_RECONNECT_ATTEMPTS: 5,
	RECONNECT_TIMEOUT: 5000,
	HEARTBEAT_INTERVAL: 30000,
	REQUEST_TIMEOUT: 30000,
	NONCE_EXPIRY_MS: 60000,
	TIMESTAMP_TOLERANCE_MS: 30000,
} as const;

export type SecurityConfig = typeof SECURITY_CONFIG;

